name: leeds_library
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.2


dependencies:
  flutter:
    sdk: flutter

  # Environment & Configuration
  flutter_dotenv: ^5.2.1

  # Dependency Injection
  get_it: ^8.0.3

  # State Management
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7
  bloc_concurrency: ^0.3.0

  # Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Routing
  go_router: ^14.7.1

  # Network & Connectivity
  connectivity_plus: ^6.1.2
  dio: ^5.8.0+1

  # Localization
  flutter_translate: ^4.1.0

  # UI & Styling
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.7
  auto_size_text: ^3.0.0
  flutter_native_splash: ^2.4.4



  # Firebase
  firebase_core: ^3.12.1
  firebase_core_web: ^2.18.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.1.0
  firebase_database: ^11.0.3
  firebase_storage: ^12.1.1
  cloud_functions: ^5.0.3
  firebase_analytics: ^11.2.0
  google_sign_in: ^6.3.0
  firebase_messaging: ^15.2.5

  cached_network_image: ^3.4.1

  shared_preferences: ^2.0.6

  # google_sign_in: ^6.2.1
  # google_sign_in_web: ^0.12.4+3

  firebase_app_check: ^0.3.1+3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

  mobile_scanner: ^3.5.7
  permission_handler: ^11.3.0
  image_picker: ^1.1.2
  rxdart: ^0.27.7

  google_mlkit_text_recognition: ^0.14.0
  camera: ^0.11.1
  flutter_tesseract_ocr: ^0.4.28

dev_dependencies:
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0



# The following section is specific to Flutter packages.
flutter:
  assets:
    - .env
    - assets/i18n/
    - assets/tessdata/
    - assets/tessdata_config.json
    - assets/images/lib_logo.png
    - assets/images/ic_collection.svg
    - assets/images/ic_scan.svg
    - assets/images/ic_settings.svg
    - assets/images/ic_menu_book.svg
    - assets/images/ic_book.svg
    - assets/images/ic_bell.svg
    - assets/images/ic_badge.svg
    - assets/images/ic_down.svg
    - assets/images/ic_account.svg
    - assets/images/ic_barcode_scanner.svg
    - assets/images/img_background.jpg
    - assets/images/star_empty.svg
    - assets/images/star_full.svg
    - assets/images/star_half.svg
    - assets/images/default_avatar.png
    - assets/images/collections_bookmark.svg
    - assets/images/google_icon.png
    - assets/images/ic_admin_panel.svg
    - assets/images/img_family.png
    - assets/images/ic_home.svg


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
